import { useState } from 'react';

export function useManaSystem() {
    const [mana, setMana] = useState<number>(100);

    const castSpell = (cost: number) =>
        {
            if (cost > mana) {
            console.warn("Not enough mana!, cost:", cost, "current mana:", mana);
            return;
        }
        setMana(m => Math.max(0, m - cost));
    };

    const regenMana = (amount: number) => {
        console.log(`Mana regenerated by ${amount}`);
        setMana(m => Math.min(100, m + amount));
    }
    

    return {
        mana,
        castSpell,
        regenMana,
        setMana
    };
}